# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CaulySwiftMediationSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Google Admob
  pod 'Google-Mobile-Ads-SDK'

  # inmobi
  pod 'GoogleMobileAdsMediationInMobi'

  # applovin
  pod 'GoogleMobileAdsMediationAppLovin'

  # vungle
  pod 'GoogleMobileAdsMediationVungle'

  # DT Exchange
  pod 'GoogleMobileAdsMediationFyber'

  # Mintegral
  pod 'GoogleMobileAdsMediationMintegral'

  # Pangle
  pod 'GoogleMobileAdsMediationPangle'

  # Unity Ads
  pod 'GoogleMobileAdsMediationUnity'

  # meta
  pod 'GoogleMobileAdsMediationFacebook'

  # adfit
  pod 'AdFitSDK'

  # Pods for CaulySwiftMediationSample

end
