# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CaulyIOSMediationSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Google Admob
  pod 'Google-Mobile-Ads-SDK', '~> 11.8.0'

  # inmobi
  pod 'GoogleMobileAdsMediationInMobi', '~> 10.7.5.0'

  # applovin
  pod 'GoogleMobileAdsMediationAppLovin', '~> 12.6.1.0'

  # vungle
  pod 'GoogleMobileAdsMediationVungle', '~> 7.4.0.1'

  # DT Exchange
  pod 'GoogleMobileAdsMediationFyber', '~> 8.3.1.0'

  # Mintegral
  pod 'GoogleMobileAdsMediationMintegral', '~> 7.7.1.0'

  # Pangle
  pod 'GoogleMobileAdsMediationPangle', '~> 6.2.0.5.0'

  # Unity Ads
  pod 'GoogleMobileAdsMediationUnity', '~> 4.12.2.0'

  # meta
  pod 'GoogleMobileAdsMediationFacebook', '~> 6.15.2.0'
  
  # Ironsource
  pod 'GoogleMobileAdsMediationIronSource', '~> 8.3.0.0.0'

  # UMP SDK
  pod 'GoogleUserMessagingPlatform', '~> 2.6.0'

  post_install do |installer|
      installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                 end
            end
     end
  end
  # Pods for CaulyIOSMediationSample

end
