# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CaulyIOSMediationSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Google Admob
  pod 'Google-Mobile-Ads-SDK', '~> 11.2.0'

  # inmobi
  pod 'GoogleMobileAdsMediationInMobi', '~> 10.7.1.0'

  # applovin
  pod 'GoogleMobileAdsMediationAppLovin', '~> 12.3.0.0'

  # vungle
  pod 'GoogleMobileAdsMediationVungle', '~> 7.3.0.0'

  # DT Exchange
  pod 'GoogleMobileAdsMediationFyber', '~> 8.2.7.0'

  # Mintegral
  pod 'GoogleMobileAdsMediationMintegral', '~> 7.5.9.0'

  # Pangle
  pod 'GoogleMobileAdsMediationPangle', '~> 5.8.0.8.0'

  # Unity Ads
  pod 'GoogleMobileAdsMediationUnity', '~> 4.10.0.0'

  # meta
  pod 'GoogleMobileAdsMediationFacebook', '~> 6.15.0.0'

  # IronSource
  pod 'GoogleMobileAdsMediationIronSource', '~>7.9.1.0.0'

  post_install do |installer|
      installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                 end
            end
     end
  end
  # Pods for CaulyIOSMediationSample

end
