# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CaulyIOSMediationSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Google Admob
  pod 'Google-Mobile-Ads-SDK'

  # Google Admob TestSuite (상용화시 반드시 삭제)
  pod 'GoogleMobileAdsMediationTestSuite'

  # inmobi
  pod 'GoogleMobileAdsMediationInMobi'

  # applovin
  pod 'GoogleMobileAdsMediationAppLovin'

  # vungle
  pod 'GoogleMobileAdsMediationVungle'

  # DT Exchange
  pod 'GoogleMobileAdsMediationFyber'

  # Mintegral
  pod 'GoogleMobileAdsMediationMintegral'

  # Pangle
  pod 'GoogleMobileAdsMediationPangle'

  # Unity Ads
  pod 'GoogleMobileAdsMediationUnity'
  
  # meta
  pod 'GoogleMobileAdsMediationFacebook'

  post_install do |installer|
      installer.generated_projects.each do |project|
            project.targets.each do |target|
                target.build_configurations.each do |config|
                    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
                 end
            end
     end
  end
  # Pods for CaulyIOSMediationSample

end
